Djangofixes
rqlite/pyrqlite pull request #28
Opened 2018-07-13 11:50 UTC by sum12

fixed to be able to use https://github.com/sum12/rqlite-django backend

2018-07-20 13:02 UTC, otoolep commented
@zmedico -- any comment?

2018-07-22 05:04 UTC, zmedico requested changes

2018-07-22 05:04 UTC, zmedico commented on src/pyrqlite/cursors.py
> +        FORMAT_QMARK_REGEX = re.compile(r'(?<!%)%s')
This isn't safe, the parameter style really needs to be adjustable in the ORM, for example sqlalchemy's SQLiteDialect declares `default_paramstyle = 'qmark'` here:

https://github.com/zzzeek/sqlalchemy/blob/rel_1_2_10/lib/sqlalchemy/dialects/sqlite/base.py#L1043

2018-07-22 05:47 UTC, zmedico commented on src/pyrqlite/cursors.py
> +        transact = ''
When automatic transactions are disabled, it probably makes sense to support the `isolation_level` parameter that python's sqlite3 module supports:

https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.isolation_level

The default behavior, `isolation_level=''`, means to implicitly issue a plain BEGIN statement before a DML statement. The parameter can be set to DEFERRED, IMMEDIATE, or EXCLUSIVE in order to make it implicitly issue the corresponding type of BEGIN statement before a DML statement. For `isolation_level=None`, autocommit mode is triggered, as described here:

https://www.sqlite.org/c3ref/get_autocommit.html

2018-08-24 19:17 UTC, zmedico commented on src/pyrqlite/connections.py
> +                 always_transactions=True, default_paramstyle='qmark'):
In my remark about default_paramstyle in sqlalchemy's SQLiteDialect, my intention was to suggest that the ORM conform to the paramstyle of the database. The existing convention is for paramstyle to be constant for a particular database type, see:

https://www.python.org/dev/peps/pep-0249/#paramstyle

2018-08-25 11:00 UTC, sum12 commented
so iiuc I can drop this change of param style, because django uses `qmark` style  for sqlite ? and that is already handled

and for the `isolation_level` iiuc, django would prefer `isolation_level=''` since it handles transactions by itself, but `pyrqlite` will have to do the right thing for other values of `isolation_level`. Did I get that right ?

2018-08-25 21:03 UTC, zmedico commented
> so iiuc I can drop this change of param style, because django uses qmark style for sqlite ? and that is already handled

Yes, if django respects the `paramstyle` value defined in src/pyrqlite/dbapi2.py then it should behave correctly without any paramstyle changes in pyrqlite.

> and for the isolation_level iiuc, django would prefer isolation_level='' since it handles transactions by itself, but pyrqlite will have to do the right thing for other values of isolation_level. Did I get that right ?

If django works correctly with the default `isolation_level=''` setting of the sqlite3 module, then it should work fine with pyrqlite too if we implement the `isolation_level` parameter.

2018-08-26 17:23 UTC, sum12 commented
I have reverted most of my changes. Thanks to @zmedico for the patiently explaining stuff. The changes related to transaction and `isolation_level` are not required after turning off a "feature flag" `autocommits_when_autocommit_is_off` in the sqlite3 backend of django

2018-08-26 23:05 UTC, zmedico commented on src/pyrqlite/cursors.py
> +        size = min(len(self._rows), size)
The size calculation looks like in could be incorrect for some corner cases. Also, the [fetchmany documentation](https://www.python.org/dev/peps/pep-0249/#fetchmany) says to use arraysize when size has not been specified, so I'd like to conform to that. How about something like this:
```python
    def fetchmany(self, size=None):
        remaining = self.arraysize if size is None else size
        remaining = min(remaining, self.rowcount - self.rownumber)
        for i in range(remaining):
            rows.append(self.fetchone())
        return rows
```

2018-09-04 05:35 UTC, zmedico commented on src/pyrqlite/cursors.py
> +        size = min(len(self._rows), size)
I've merged the Row slice change in aa562e4942531e96a13b927b69be4bdf9ed6cc43, and the cursor factory change in 9da1eb12c66e73b425b70523984517ec744d3a5a.

2018-09-04 06:11 UTC, closed without merging

2018-09-04 06:15 UTC, zmedico commented
Changes merged in aa562e4942531e96a13b927b69be4bdf9ed6cc43, 9da1eb12c66e73b425b70523984517ec744d3a5a, and f8cd41e0522af36a234088b3c876ccfc5078f662. Thanks!